### ISSUE TITLE
Minor issues with current master branch of RIOT-OS

### ISSUE THREAD

**Issue by jue89** [seeseemelk/openocd#1]
*First of all: Thanks for rebasing and fixing the Arch AUR build :)*

Some minor issues I found while debugging the latest master branch of RIOT-OS (https://github.com/RIOT-OS/RIOT/commit/7150c7ae10d9a277be2f067b545de42126a003d4).

---

https://github.com/seeseemelk/openocd/blob/ab43818d9014f37c1f9c92619805456410431e04/src/rtos/riot.c#L35

This symbol is never set. Quick fix could be testing whether the symbol `_tcb_name_offset` is present. It is defined here:
https://github.com/RIOT-OS/RIOT/blob/7150c7ae10d9a277be2f067b545de42126a003d4/core/sched.c#L67-L72

---

https://github.com/seeseemelk/openocd/blob/ab43818d9014f37c1f9c92619805456410431e04/src/rtos/riot.c#L177-L178

This won't detect RIOT if it is built without `DEVELHELP=1`. I'd recommend to test only the symbols `"sched_num_threads"` and `"sched_threads"`.

**Comment by seeseemelk** [comment]
For the first part, I was looking for a symbol that I could use to detect DEVELHELP, but I couldn't find any (was looking by comparing binaries and arm-none-eabi-objcopy). I think that the version of RIOT I was using at the time did not have that symbol yet, so I manually added the `built_with_develhelp` symbol in my `main.c` file with a little `#ifdef` around it. That was the only way I knew at the time to reliably detect `DEVELHELP`.

And you're right about the second part, I have my `openocd.cfg` set to always use RIOT, so I never really tested if the detection works.

**Comment by seeseemelk** [comment]
It's probably worth mentioning that there is also some upstream work to get a RIOT support in OpenOCD (http://openocd.zylin.com/#/c/4256/), although I haven't tried it myself yet.
